"""Compare Python Apodization with MATLAB uff.apodization, pixel by pixel.

Requires apodization_reference.h5 generated by generate_apodization_reference.m
and the PICMUS / Verasonics datasets in data/.
Run with: pytest tests/test_apodization_vs_matlab.py -v
"""

import os
import numpy as np
import pytest
import h5py

from tests.matlab_compare import match_pixels
from ustb.apodization import Apodization
from ustb.enums import Window

REFERENCE_FILE = os.path.join(os.path.dirname(__file__), "apodization_reference.h5")
DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "data")
PICMUS_FILE = os.path.join(DATA_DIR, "PICMUS_experiment_resolution_distortion.uff")
PHASED_FILE = os.path.join(DATA_DIR, "Verasonics_P2-4_parasternal_long_small.uff")

pytestmark = pytest.mark.skipif(
    not all(os.path.exists(f) for f in (REFERENCE_FILE, PICMUS_FILE, PHASED_FILE)),
    reason="MATLAB apodization reference or datasets not available",
)

ALL_WINDOWS = ["boxcar", "hanning", "hamming", "tukey25", "tukey50", "tukey75", "triangle"]
LIMITS = dict(minimum_aperture=[3e-3, 3e-3], maximum_aperture=[20e-3, 20e-3],
              grating_lobe_angle=[0.6, 0.6])

# (reference dataset, geometry, window, f-number, extra settings)
CASES = (
    [(f"tx_plane/{w}", "tx_plane", w, 1.7, {}) for w in ALL_WINDOWS]
    + [("tx_plane/tukey50_tilt", "tx_plane", "tukey50", 1.7, dict(tilt=[0.05, 0]))]
    + [(f"tx_div/{w}", "tx_div", w, 1.2, {}) for w in ["hanning", "tukey50", "boxcar"]]
    + [("tx_div/tukey50_limits", "tx_div", "tukey50", 1.2, LIMITS)]
    + [(f"rx_linear/{w}", "rx_linear", w, 1.7, {}) for w in ALL_WINDOWS]
    + [("rx_linear/hamming_tilt_limits", "rx_linear", "hamming", 1.4,
        dict(tilt=[0.1, 0], minimum_aperture=[4e-3, 4e-3], maximum_aperture=[15e-3, 15e-3]))]
    + [(f"sector/{w}", "sector", w, 1.5, {}) for w in ["hanning", "tukey25"]]
)


class _Point:
    def __init__(self, xyz):
        self.x, self.y, self.z = (float(v) for v in xyz)
        self.distance = float(np.linalg.norm(xyz))
        self.azimuth = float(np.arctan2(self.x, self.z))
        self.elevation = 0.0


class _SphericalWave:
    def __init__(self, source, origin):
        self.source, self.origin, self.wavefront = _Point(source), _Point(origin), 1


@pytest.fixture(scope="module")
def setup():
    from pyuff_ustb.objects.uff import Uff
    from pyuff_ustb.objects import SectorScan
    from pyuff_ustb.objects.point import Point

    ref = h5py.File(REFERENCE_FILE, "r")
    picmus = Uff(PICMUS_FILE)
    channel_data = picmus.read("channel_data")
    linear_scan = picmus.read("scan")
    plane_waves = channel_data.sequence
    if not isinstance(plane_waves, (list, tuple)):
        plane_waves = [plane_waves]

    # Diverging waves defined in the MATLAB script (h5py reads them as [wave, xyz])
    sources, origins = ref["tx_div/source"][:], ref["tx_div/origin"][:]
    diverging_waves = [_SphericalWave(s, o) for s, o in zip(sources, origins)]

    sector_scan = SectorScan()
    sector_scan.__dict__["azimuth_axis"] = ref["sector/azimuth_axis"][:].ravel()
    sector_scan.__dict__["depth_axis"] = ref["sector/depth_axis"][:].ravel()
    apex = Point()
    apex.__dict__.update(distance=np.float64(0.0), azimuth=np.float64(0.0),
                         elevation=np.float64(0.0))
    sector_scan.__dict__["origin"] = apex

    linear_perm = match_pixels((ref["linear/x"][:], ref["linear/z"][:]),
                               (linear_scan.x, linear_scan.z))
    sector_perm = match_pixels((ref["sector/x"][:], ref["sector/z"][:]),
                               (sector_scan.x, sector_scan.z))
    geometries = {
        "tx_plane": dict(sequence=plane_waves, focus=linear_scan, perm=linear_perm),
        "tx_div": dict(sequence=diverging_waves, focus=linear_scan, perm=linear_perm),
        "rx_linear": dict(probe=channel_data.probe, focus=linear_scan, perm=linear_perm),
        "sector": dict(probe=Uff(PHASED_FILE).read("channel_data").probe,
                       focus=sector_scan, perm=sector_perm),
    }
    yield ref, geometries
    ref.close()


@pytest.mark.parametrize("key, geometry, window, f_number, extra", CASES,
                         ids=[case[0] for case in CASES])
def test_should_match_matlab_apodization(setup, key, geometry, window, f_number, extra):
    ref, geometries = setup
    geo = geometries[geometry]

    apo = Apodization()
    apo.window = Window[window]
    apo.f_number = np.array([f_number, f_number])
    for name, value in extra.items():
        setattr(apo, name, np.array(value, dtype=float))
    apo.focus = geo["focus"]
    apo.probe = geo.get("probe")
    apo.sequence = geo.get("sequence")

    ml = ref[key][:].T[geo["perm"]]  # -> [pixel, element or wave], Python pixel order
    np.testing.assert_allclose(apo.data, ml, rtol=0, atol=1e-5,
                               err_msg=f"{key} differs from MATLAB")
