"""Integration tests comparing Python DAS output against MATLAB reference.

Requires matlab_reference.h5 generated by generate_matlab_reference.m.
Run with: pytest tests/test_integration_matlab.py -v
"""

import os
import numpy as np
import pytest
import h5py

from tests.matlab_compare import match_pixels, assert_pixelwise_match

REFERENCE_FILE = os.path.join(os.path.dirname(__file__), "matlab_reference.h5")
DATA_FILE = os.path.join(os.path.dirname(__file__), "..", "..", "data",
                         "Verasonics_P2-4_parasternal_long_small.uff")

pytestmark = pytest.mark.skipif(
    not os.path.exists(REFERENCE_FILE) or not os.path.exists(DATA_FILE),
    reason="MATLAB reference data or UFF dataset not available"
)


@pytest.fixture(scope="module")
def matlab_ref():
    """Load MATLAB reference data."""
    with h5py.File(REFERENCE_FILE, "r") as f:
        return {
            "scan_x": f["scan/x"][:].ravel(),
            "scan_y": f["scan/y"][:].ravel(),
            "scan_z": f["scan/z"][:].ravel(),
            "transmit_delay": f["transmit_delay"][:].T,
            "receive_delay": f["receive_delay"][:].T,
            "bf_real": f["beamformed_data_real"][:].T,
            "bf_imag": f["beamformed_data_imag"][:].T,
            "N_pixels": int(np.squeeze(f["N_pixels"][()])),
            "N_waves": int(np.squeeze(f["N_waves"][()])),
            "N_channels": int(np.squeeze(f["N_channels"][()])),
        }


@pytest.fixture(scope="module")
def python_result(matlab_ref):
    """Run Python DAS on the same dataset with matching parameters."""
    from pyuff_ustb.objects.uff import Uff
    from pyuff_ustb.objects import SectorScan
    from pyuff_ustb.objects.point import Point
    from ustb.midprocess import DAS
    from ustb.enums import Dimension, Window

    uff_file = Uff(DATA_FILE)
    channel_data = uff_file.read("channel_data")

    sequence = channel_data.sequence
    if not isinstance(sequence, (list, tuple)):
        sequence = [sequence]

    depth_axis = np.linspace(0e-3, 110e-3, 128)
    first_az = float(sequence[0].source.azimuth)
    last_az = float(sequence[-1].source.azimuth)
    azimuth_axis = np.linspace(first_az, last_az, len(sequence))

    scan = SectorScan()
    scan.__dict__["azimuth_axis"] = azimuth_axis
    scan.__dict__["depth_axis"] = depth_axis
    origin = Point()
    origin.__dict__["distance"] = np.float64(0.0)
    origin.__dict__["azimuth"] = np.float64(0.0)
    origin.__dict__["elevation"] = np.float64(0.0)
    scan.__dict__["origin"] = origin

    mid = DAS()
    mid.channel_data = channel_data
    mid.dimension = Dimension.both
    mid.scan = scan
    mid.transmit_apodization.window = Window.scanline
    mid.receive_apodization.window = Window.none
    b_data = mid.go()

    return {
        "scan_x": scan.x.ravel(),
        "scan_y": scan.y.ravel(),
        "scan_z": scan.z.ravel(),
        "transmit_delay": mid.transmit_delay,
        "receive_delay": mid.receive_delay,
        "bf_data": b_data.data,
    }


@pytest.fixture(scope="module")
def perm(matlab_ref, python_result):
    """MATLAB pixel index for each Python pixel (the two orderings differ)."""
    return match_pixels(
        (matlab_ref["scan_x"], matlab_ref["scan_y"], matlab_ref["scan_z"]),
        (python_result["scan_x"], python_result["scan_y"], python_result["scan_z"]),
    )


class TestScanCoordinates:
    def test_should_contain_the_same_pixel_positions(self, perm):
        """Every Python pixel has a MATLAB pixel at the same position (checked in match_pixels)."""
        assert len(np.unique(perm)) == len(perm)


class TestReceiveDelay:
    def test_should_match_matlab_per_pixel(self, matlab_ref, python_result, perm):
        np.testing.assert_allclose(
            python_result["receive_delay"], matlab_ref["receive_delay"][perm],
            rtol=1e-5, atol=1e-10, err_msg="Receive delay differs from MATLAB",
        )


class TestTransmitDelay:
    def test_should_match_matlab_per_pixel(self, matlab_ref, python_result, perm):
        np.testing.assert_allclose(
            python_result["transmit_delay"], matlab_ref["transmit_delay"][perm],
            rtol=1e-5, atol=1e-10, err_msg="Transmit delay differs from MATLAB",
        )


class TestBeamformedOutput:
    def test_should_have_matching_shape(self, matlab_ref, python_result):
        assert python_result["bf_data"].shape == matlab_ref["bf_real"].shape

    def test_should_match_matlab_per_pixel(self, matlab_ref, python_result, perm):
        """Beamformed IQ data should match MATLAB pixel by pixel.

        The pixels at depth 0 are excluded: they all sit at the probe origin,
        where the Python scanline apodization (based on pixel azimuth angle)
        assigns them all to the centre scanline, while MATLAB assigns them by
        azimuth index. Everywhere else the two implementations agree.
        """
        ml_bf = (matlab_ref["bf_real"] + 1j * matlab_ref["bf_imag"])[perm]
        depth = np.hypot(python_result["scan_x"], python_result["scan_z"])
        assert_pixelwise_match(
            ml_bf, python_result["bf_data"], "Verasonics P2-4 sector scan",
            min_corr=0.99999, max_rel_err=1e-3, mask=depth > 1e-9,
        )
