"""Integration tests comparing Python examples against MATLAB reference output.

Each test loads the MATLAB reference HDF5 (generated by generate_all_references.m),
runs the matching Python example, pairs the pixels by position (MATLAB and Python
order them differently) and compares the beamformed data pixel by pixel.
"""

import os
import numpy as np
import pytest
import h5py

from tests.matlab_compare import match_pixels, assert_pixelwise_match

REF_DIR = os.path.dirname(__file__)
DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "data")


# Pixelwise agreement required for every example
MIN_ENVELOPE_CORR = 0.999
MAX_RELATIVE_ERROR = 1e-2


# The Python Apodization does not implement transmit windows other than none and
# scanline (it returns all ones), so the PICMUS examples, which use a tukey50
# transmit window with f-number 1.7, differ from MATLAB: envelope correlation
# 0.986-0.995 and ~25% relative complex error. strict=True makes these tests
# fail once transmit apodization is implemented, so the marker gets removed.
xfail_transmit_apodization = pytest.mark.xfail(
    strict=True,
    reason="Python transmit apodization ignores windows other than none/scanline",
)


def assert_matches_matlab(ref_file, b_data, name):
    """Compare Python beamformed data with the MATLAB reference, pixel by pixel."""
    with h5py.File(ref_file, "r") as f:
        ml_bf = (f["bf_real"][:] + 1j * f["bf_imag"][:]).T  # -> [pixel, ch, wave, frame]
        ml_x, ml_z = f["scan_x"][:], f["scan_z"][:]
    perm = match_pixels((ml_x, ml_z), (b_data.scan.x, b_data.scan.z))
    assert_pixelwise_match(ml_bf[perm], b_data.data, name,
                           min_corr=MIN_ENVELOPE_CORR, max_rel_err=MAX_RELATIVE_ERROR)


class TestCPWCLinear:
    REF = os.path.join(REF_DIR, "ref_cpwc_linear.h5")
    DATA = os.path.join(DATA_DIR, "L7_CPWC_193328.uff")

    @pytest.fixture(scope="class")
    def result(self):
        if not os.path.exists(self.DATA):
            pytest.skip("Dataset not available")
        from examples.cpwc_linear import main
        import matplotlib; matplotlib.use("Agg")
        return main()

    @pytest.mark.skipif(not os.path.exists(REF), reason="Reference not available")
    def test_should_match_matlab_per_pixel(self, result):
        assert_matches_matlab(self.REF, result, "CPWC Linear")

    def test_should_produce_nonzero_output(self, result):
        assert np.abs(result.data).max() > 0

    def test_should_have_correct_pixel_count(self, result):
        assert result.data.shape[0] == 256 * 256


class TestPICMUSExperimentResolution:
    REF = os.path.join(REF_DIR, "ref_picmus_exp_resolution.h5")
    DATA = os.path.join(DATA_DIR, "PICMUS_experiment_resolution_distortion.uff")

    @pytest.fixture(scope="class")
    def result(self):
        if not os.path.exists(self.DATA):
            pytest.skip("Dataset not available")
        from examples.picmus_experiment_resolution import main
        import matplotlib; matplotlib.use("Agg")
        return main()

    @pytest.mark.skipif(not os.path.exists(REF), reason="Reference not available")
    @xfail_transmit_apodization
    def test_should_match_matlab_per_pixel(self, result):
        assert_matches_matlab(self.REF, result, "PICMUS Exp Resolution")

    def test_should_produce_nonzero_output(self, result):
        assert np.abs(result.data).max() > 0


class TestPICMUSSimulationResolution:
    REF = os.path.join(REF_DIR, "ref_picmus_sim_resolution.h5")
    DATA = os.path.join(DATA_DIR, "PICMUS_simulation_resolution_distortion.uff")

    @pytest.fixture(scope="class")
    def result(self):
        if not os.path.exists(self.DATA):
            pytest.skip("Dataset not available")
        from examples.picmus_simulation_resolution import main
        import matplotlib; matplotlib.use("Agg")
        return main()

    @pytest.mark.skipif(not os.path.exists(REF), reason="Reference not available")
    @xfail_transmit_apodization
    def test_should_match_matlab_per_pixel(self, result):
        assert_matches_matlab(self.REF, result, "PICMUS Sim Resolution")

    def test_should_produce_nonzero_output(self, result):
        assert np.abs(result.data).max() > 0


class TestPICMUSExperimentContrast:
    REF = os.path.join(REF_DIR, "ref_picmus_exp_contrast.h5")
    DATA = os.path.join(DATA_DIR, "PICMUS_experiment_contrast_speckle.uff")

    @pytest.fixture(scope="class")
    def result(self):
        if not os.path.exists(self.DATA):
            pytest.skip("Dataset not available")
        from examples.picmus_experiment_contrast import main
        import matplotlib; matplotlib.use("Agg")
        return main()

    @pytest.mark.skipif(not os.path.exists(REF), reason="Reference not available")
    @xfail_transmit_apodization
    def test_should_match_matlab_per_pixel(self, result):
        assert_matches_matlab(self.REF, result, "PICMUS Exp Contrast")

    def test_should_produce_nonzero_output(self, result):
        assert np.abs(result.data).max() > 0


class TestPICMUSSimulationContrast:
    REF = os.path.join(REF_DIR, "ref_picmus_sim_contrast.h5")
    DATA = os.path.join(DATA_DIR, "PICMUS_simulation_contrast_speckle.uff")

    @pytest.fixture(scope="class")
    def result(self):
        if not os.path.exists(self.DATA):
            pytest.skip("Dataset not available")
        from examples.picmus_simulation_contrast import main
        import matplotlib; matplotlib.use("Agg")
        return main()

    @pytest.mark.skipif(not os.path.exists(REF), reason="Reference not available")
    @xfail_transmit_apodization
    def test_should_match_matlab_per_pixel(self, result):
        assert_matches_matlab(self.REF, result, "PICMUS Sim Contrast")

    def test_should_produce_nonzero_output(self, result):
        assert np.abs(result.data).max() > 0
